# Generated by Django 4.2.6 on 2024-03-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconicities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
