# Generated by Django 4.2.6 on 2024-05-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconicities', '0002_stimulus_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stimulus',
            name='is_active',
        ),
        migrations.AddField(
            model_name='stimulus',
            name='group',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('i', 'Inactive')], default='a', max_length=2, verbose_name='Group'),
        ),
    ]
