# Generated by Django 4.2.6 on 2024-05-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconicities', '0003_remove_stimulus_is_active_stimulus_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='a',
            field=models.BooleanField(default=True, verbose_name='a'),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='b',
            field=models.BooleanField(default=False, verbose_name='b'),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='c',
            field=models.BooleanField(default=False, verbose_name='c'),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='d',
            field=models.BooleanField(default=False, verbose_name='d'),
        ),
    ]
