# Generated by Django 4.2.6 on 2024-05-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconicities', '0004_stimulus_a_stimulus_b_stimulus_c_stimulus_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stimulus',
            name='a',
        ),
        migrations.RemoveField(
            model_name='stimulus',
            name='b',
        ),
        migrations.RemoveField(
            model_name='stimulus',
            name='c',
        ),
        migrations.RemoveField(
            model_name='stimulus',
            name='d',
        ),
        migrations.RemoveField(
            model_name='stimulus',
            name='group',
        ),
        migrations.AddField(
            model_name='stimulus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
