# Generated by Django 4.2.6 on 2024-10-08 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconicities', '0005_remove_stimulus_a_remove_stimulus_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='lsu_fluency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='LSU fluency'),
        ),
    ]
