# Generated by Django 4.2.6 on 2024-10-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconicities', '0006_form_lsu_fluency'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='control',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Control'),
        ),
    ]
