# Generated by Django 4.2.6 on 2024-10-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconicities', '0006_form_lsu_fluency'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='is_control',
            field=models.BooleanField(default=False, verbose_name='Is control'),
        ),
    ]
